//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTPMHDV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HINHANH
    {
        public string MaAnh { get; set; }
        public string KichThuoc { get; set; }
        public string MaSP { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
